/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/cloud2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud(props) {
  const { nodes, materials } = useGLTF('/assets/models/cloud2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.001']} position={[-2.003, -1.191, 2.14]} rotation={[0.043, 0.007, -3.139]} scale={-0.684} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.001']} position={[-3.376, -0.968, 0.497]} rotation={[-0.012, 0.001, -3.141]} scale={-0.598} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials['Material.001']} position={[-3.59, -1.084, -1.932]} rotation={[0.075, 0.001, -3.141]} scale={-0.736} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials['Material.001']} position={[-4.462, -0.075, -0.111]} rotation={[-0.135, 0.047, 2.811]} scale={-0.997} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials['Material.001']} position={[-4.462, 0.456, 2.146]} rotation={[-3.086, -0.888, 0.24]} scale={-0.95} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials['Material.001']} position={[-4.462, 1.156, -1.981]} rotation={[0.282, -0.001, 0]} scale={0.688} />
    </group>
  )
}

useGLTF.preload('/assets/models/cloud2.glb')
