/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/test4.glb 
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const Cloud = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/src/assets/models/cloud.glb');
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cloud.geometry}
        material={materials['Material.001']}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={1}
      />
    </group>
  );
});

useGLTF.preload('/src/assets/models/cloud.glb');
