version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:rootpassword@mysql:3306/mydb
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000
      - FRONTEND_URL=http://localhost:5173
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASSWORD=your_email_password
      - EMAIL_FROM=your_email@gmail.com
      - SEED_DATABASE=true
    networks:
      - app_network
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:

